[dispatcher]
### kafka ###
"brokers" = [ "10.200.252.180:9092", "10.200.252.181:9092", "10.200.252.182:9092"]
#"topic_partition_num" = ""
#"topic_replication_num" = ""
# "msg_max_bytes" = 0

### consumer ###
"group_id" = "kevin_testing_group_2"

### tls ###
#"tls_enable" = ""
#"verifySsl" = ""
#"cert_file" = ""
#"key_file" = ""
#"ca_file" = ""

### testing ###
"testCount" = ""
"topic" = "disp.testing"
log_level = "trace"

# [log]
# "level" = info
# "level" = "debug"